### ISSUE TITLE
[Karma]Не запускаются тесты

### ISSUE THREAD

**Issue by bmsdave** [hacad/dronecafe#1]
При запуске "npm run test" возникает ошибка:

```
λ npm run test

> dronecafe@0.1.0 test C:\Users\vgorbachev\project\test\dronecafe
> karma start test/unit/karma.conf.js

08 07 2017 22:39:37.368:WARN [watcher]: Pattern "C:/Users/vgorbachev/project/test/dronecafe/public/assets/bower_components/angular-mocks/angular-mocks.js" does not match any file.
08 07 2017 22:39:37.423:WARN [karma]: No captured browser, open http://localhost:9876/
08 07 2017 22:39:37.440:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
08 07 2017 22:39:37.442:INFO [launcher]: Launching browser Chrome with unlimited concurrency
08 07 2017 22:39:37.466:INFO [launcher]: Starting browser Chrome
08 07 2017 22:39:39.207:INFO [Chrome 59.0.3071 (Windows 10 0.0.0)]: Connected on socket pVOOjRYuBRpiGA6OAAAA with id 24016483
Chrome 59.0.3071 (Windows 10 0.0.0) UserDashboardCtrl encountered a declaration exception FAILED
        ReferenceError: module is not defined
            at Suite.<anonymous> (UserDashboardCtrlTest.js:3:3)
            at UserDashboardCtrlTest.js:1:1
Chrome 59.0.3071 (Windows 10 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.015 secs / 0.004 secs)
```

**Comment by hacad** [comment]
not reproducing
